# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100, verbose_name='Nome')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=25, verbose_name='Numero')),
                ('emissao', models.DateTimeField(auto_now_add=True, verbose_name='Emissao')),
                ('vencimento', models.DateTimeField(auto_now_add=True, verbose_name='Vencimento')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=25, verbose_name='Numero')),
                ('emissao', models.DateTimeField(auto_now_add=True, verbose_name='Emissao')),
                ('vencimento', models.DateTimeField(auto_now_add=True, verbose_name='Vencimento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='EmailCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Cliente')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Cep')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('complemento', models.CharField(default='nulo', max_length=2048, verbose_name='Complemento')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Numero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Cliente')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='EnderecoFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Cep')),
                ('tipo', models.CharField(default='nulo', max_length=100, verbose_name='Tipo')),
                ('descricao', models.CharField(default='nulo', max_length=2048, verbose_name='Descricao')),
                ('complemento', models.CharField(default='nulo', max_length=2048, verbose_name='Complemento')),
                ('numero', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Parcela')),
                ('valorparcela', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ValorParcela')),
                ('quantidade', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_pago', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor_pago')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Finaceiros',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100, verbose_name='Nome')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor')),
                ('foto', models.ImageField(blank=True, default='fornecedor/static/imagens/default.jpg', null=True, upload_to='produto/')),
                ('descricao', models.CharField(default='nulo', max_length=500, verbose_name='Descricao')),
                ('estoque', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Financeiro')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Produto')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='enderecofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor'),
        ),
        migrations.AddField(
            model_name='emailfornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor'),
        ),
        migrations.AddField(
            model_name='documentofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor'),
        ),
    ]
