# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venda',
            new_name='VendaProduto',
        ),
    ]
