# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_auto_20160528_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='financeiro',
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='parcela',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_pago',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor_pago'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valorparcela',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='ValorParcela'),
        ),
    ]
