# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_auto_20160528_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='username',
            field=models.CharField(default='nulo', max_length=100, verbose_name='username'),
        ),
    ]
