# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0004_auto_20160528_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000000L, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedor/static/imagens/default.jpg', max_length=100000, null=True, upload_to='produto/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000000L, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=100000000000L, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_pago',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000000L, verbose_name='Valor_pago'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valorparcela',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000000000L, verbose_name='ValorParcela'),
        ),
    ]
